# Generated by Django 4.0.1 on 2022-01-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_deportista_name_alter_deportista_respuesta_depor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deportista',
            name='respuesta',
        ),
    ]
