# Generated by Django 4.0.1 on 2022-01-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_contact_dxt_alter_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='observaciones',
            field=models.CharField(default='', max_length=150),
        ),
    ]
