# Generated by Django 4.0.1 on 2022-01-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_dia1_comensal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia1',
            name='b',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='dia1',
            name='d',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='dia1',
            name='l',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='dia1',
            name='m',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
