# Generated by Django 4.0.1 on 2022-02-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_comensal_opciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariablesGlobales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diadxt', models.CharField(default='Domingo', max_length=20)),
            ],
        ),
    ]
