# Generated by Django 4.0.1 on 2022-02-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_variablesglobales_diadxt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablesglobales',
            name='diadxt',
            field=models.IntegerField(default=6),
        ),
    ]
