# Generated by Django 4.0.1 on 2022-02-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='recurso',
            field=models.FileField(blank=True, null=True, upload_to='recursos/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='FotosRecursos/', verbose_name='Imagen'),
        ),
    ]
