# Generated by Django 4.0.1 on 2022-02-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_recurso_recurso_alter_recurso_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurso',
            options={'ordering': ['fecha_creacion'], 'verbose_name': 'Recurso', 'verbose_name_plural': 'Recursos'},
        ),
    ]
