# Generated by Django 4.0.1 on 2022-03-02 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0026_remove_deportista_olduser_deportista_user1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deportista',
            name='user1',
        ),
        migrations.AlterField(
            model_name='deportista',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
