# Generated by Django 4.0.1 on 2022-03-02 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0027_remove_deportista_user1_alter_deportista_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deportista',
            name='user',
        ),
        migrations.AddField(
            model_name='deportista',
            name='user1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
