# Generated by Django 4.0.1 on 2022-03-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_remove_deportista_user_deportista_user1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deportista',
            name='user1',
        ),
        migrations.AddField(
            model_name='deportista',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
