# Generated by Django 4.0.1 on 2022-03-02 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0030_remove_deportista_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportista',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deportista',
            name='user1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
