# Generated by Django 4.0.1 on 2022-03-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_alter_comensal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comensal',
            name='user1',
            field=models.CharField(default='', max_length=100),
        ),
    ]
