# Generated by Django 4.0.1 on 2022-03-02 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_alter_comensal_user_alter_comensal_user1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comensal',
            name='user1',
        ),
    ]
