# Generated by Django 3.2.3 on 2022-04-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_alter_comensal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablesglobales',
            name='diaparte',
            field=models.IntegerField(default=6),
        ),
    ]