# Generated by Django 4.0.1 on 2022-04-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_alter_comensal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablesglobales',
            name='diaparte',
            field=models.IntegerField(default=6),
        ),
    ]
