# Generated by Django 3.2.3 on 2022-05-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_variablesglobales_diaparte'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='variablesglobales',
            table='VARIABLES',
        ),
    ]