# Generated by Django 4.0.1 on 2022-05-21 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0041_alter_variablesglobales_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablesglobales',
            name='precio_dblanco',
            field=models.DecimalField(decimal_places=2, default=0.09, max_digits=5),
        ),
        migrations.AddField(
            model_name='variablesglobales',
            name='precio_dcolor',
            field=models.DecimalField(decimal_places=2, default=0.18, max_digits=5),
        ),
        migrations.AddField(
            model_name='variablesglobales',
            name='precio_iblanco',
            field=models.DecimalField(decimal_places=2, default=0.06, max_digits=5),
        ),
        migrations.AddField(
            model_name='variablesglobales',
            name='precio_icolor',
            field=models.DecimalField(decimal_places=2, default=0.12, max_digits=5),
        ),
        migrations.AddField(
            model_name='variablesglobales',
            name='precio_tblanco',
            field=models.DecimalField(decimal_places=2, default=0.03, max_digits=5),
        ),
        migrations.AddField(
            model_name='variablesglobales',
            name='precio_tcolor',
            field=models.DecimalField(decimal_places=2, default=0.06, max_digits=5),
        ),
        migrations.AlterModelTable(
            name='variablesglobales',
            table=None,
        ),
        migrations.CreateModel(
            name='Impresor',
            fields=[
                ('msg_id3', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('texto_blanco', models.PositiveIntegerField(default=0)),
                ('texto_color', models.PositiveIntegerField(default=0)),
                ('imagen_blanco', models.PositiveIntegerField(default=0)),
                ('imagen_color', models.PositiveIntegerField(default=0)),
                ('denso_blanco', models.PositiveIntegerField(default=0)),
                ('denso_color', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]