# Generated by Django 4.0.1 on 2022-05-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_variablesglobales_precio_dblanco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresor',
            name='e10',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impresor',
            name='e14',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impresor',
            name='e20',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impresor',
            name='e6',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impresor',
            name='tapas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
